FROM node:18-alpine as base

WORKDIR /app

COPY package*.json .
COPY tsconfig.json .
COPY tsconfig.build.json .

RUN npm ci

COPY . .

RUN npm run build

FROM node:18-alpine as production

WORKDIR /app

COPY package*.json .

RUN npm ci --only=production

COPY --from=base /app/dist ./dist

ENV NODE_ENV=production

CMD npm run start